Upgrade Django from 1.11 to 2.0
UPGRADE: models.py: add on_delete option to ForeignKey as required by Django 2
UPGRADE: views.py: import reverse from a different Django package as required by Django 2
CHANGE: migrations: for emailusername and questions apps:
  - remove existing migrations
  - recreate new initial migrations
CHANGE: settings.py: change MIDDLEWARE_CLASSES to MIDDLEWARE
  Django 2.0 removed support for MIDDLEWARE_CLASSES
  This fixes the issue:
        AttributeError: 'WSGIRequest' object has no attribute 'user'
UPGRADE: Pipfile: splinter pinned at 0.8.0
  Note that phantomjs support in splinter was removed in 0.9.0, so I
  pinned it at 0.8.0.
CHANGE: Pipfile: add selenium and splinter as dev-packages
UPGRADE: Pipfile: psycopg2: upgrade from 2.7.3.2 to 2.7.4
UPGRADE: Pipfile: pytz: upgrade from 2017.3 to 2018.3
UPGRADE: Pipfile: pythong-dateutil: upgrade from 2.6.1 to 2.72
UPGRADE: Pipfile: Django: upgrade from 1.11.0 to 2.0.3
UPGRADE: Pipfile: python_version: upgrade from 2.7 to 3.7
  Note that I updated the code in previous commits and tested
  with python 3.  This change is for the Pipfile, whereas I
  might not have used the Pipfile earlier when testing with
  Python 3.
CHANGE: Makefile: modify dumpdb so that it sets DB_QUIZME env var
requirements*.txt: removed them; using only Pipfile now
.gitignore: add comment