UPGRADE to Django 3: Pipfile* -- upgrade ALL packages to latest (except splinter) (BROKEN)
Upgrade all packages to their latest versions (including Django from 2
to 3), except for splinter.

splinter is pinned to the last version that supports phantomjs.
phantomjs will be removed in a future commit and replaced with headless.

NOTE: this commit is broken.  Issues will be fixed one-by-one in
subsequent commits. Error when running runserver:

File "/Users/rbednark/quizme-read-only-prod/questions/models.py", line 2, in <module>
    from django.utils.encoding import python_2_unicode_compatible
ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding' (/Users/rbednark/.virtualenvs/quizme-read-only-prod-7Es8yr1p/lib/python3.7/site-packages/django/utils/encoding.py)