UPGRADE to Django 3: fix auth login issue (BROKEN)
With the upgrade to Django 3, the Django login view was moved.
Fixed this by:
a) get login view from new location
b) move login.html template
     from questions/templates
     to   questions/templates/questions
c) eliminate using emailusername.views.login for the login view

Error that this fixes:
  File "/Users/rbednark/quizme-read-only-prod/emailusername/views.py", line 1, in <module>
    from django.contrib.auth.views import (login as django_login,
  ImportError: cannot import name 'login' from 'django.contrib.auth.views' (/Users/rbednark/.virtualenvs/quizme-read-only-prod-7Es8yr1p/lib/python3.7/site-packages/django/contrib/auth/views.py)

NOTE: this commit is BROKEN.  Issues will be fixed one-by-one in subsequent
commits.  runserver runs, but get the following error for the http://127.0.0.1:8000/question/ page:
  File "/Users/rbednark/quizme-read-only-prod/questions/views.py", line 377, in question
    ).latest(field_name='datetime_added')
  TypeError: latest() got an unexpected keyword argument 'field_name'