UPGRADE to Django 3: questions/models.py: fix python_2_unicode_compatible import source (BROKEN)
With the Django upgrade from 2 to 3, need to import python_2_unicode_compatible from
six instead of django.utils.encoding.

Error that this fixes:
    ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding' (/Users/rbednark/.virtualenvs/quizme-read-only-prod-7Es8yr1p/lib/python3.7/site-packages/django/utils/encoding.py)

Reference:
    https://stackoverflow.com/questions/20741754/python-2-unicode-compatible-error

NOTE: this commit is BROKEN.  Issues will be fixed one-by-one in subsequent
commits.  Error when running runserver:

File "/Users/rbednark/quizme-read-only-prod/emailusername/views.py", line 1, in <module>
    from django.contrib.auth.views import (login as django_login,
ImportError: cannot import name 'login' from 'django.contrib.auth.views' (/Users/rbednark/.virtualenvs/quizme-read-only-prod-7Es8yr1p/lib/python3.7/site-packages/django/contrib/auth/views.py)